Házi feladat javítás utáni
A  http://localhost:8080/frontapp?message=Hello hivas eredmenye:
{
    "msForReply": 120,
    "backappMessage": "hardcoded-default-backapp-message",
    "frontappHomeworkOwner": "Dézsi Lajos",
    "frontappHostAddress": "172.22.0.2",
    "backappHomeworkOwner": "Dézsi Lajos",
    "backappHostAddress": "172.22.0.3",
    "doExtraImageDataMatch": true
}
és a hivashoz kapcsolodó log:
frontend-1  | 2024-04-15T19:30:37.164Z  INFO 1 --- [nio-8080-exec-7] h.c.c.api.controller.FrontappController  : Calling backapp
backend-1   | 2024-04-15T19:30:37.167Z  INFO 1 --- [nio-8080-exec-4] hu.cubix.cloud.api.BackappController     : Request arrived with message
backend-1   | 2024-04-15T19:30:37.167Z  INFO 1 --- [nio-8080-exec-4] hu.cubix.cloud.api.BackappController     : Message was empty, fall back to default    
backend-1   | 2024-04-15T19:30:37.167Z  INFO 1 --- [nio-8080-exec-4] hu.cubix.cloud.api.BackappController     : Default message was empty, falling back to hardcoded default
backend-1   | 2024-04-15T19:30:37.168Z  INFO 1 --- [nio-8080-exec-4] hu.cubix.cloud.api.BackappController     : Returning response: BackappResponse[time=2024-04-15T19:30:37.167862151, message=hardcoded-default-backapp-message, homeworkOwner=Dézsi Lajos, hostAddress=172.22.0.3, extraImageData=Cubix training]  
frontend-1  | 2024-04-15T19:30:37.170Z  INFO 1 --- [nio-8080-exec-7] h.c.c.api.controller.FrontappController  : Backapp call was successful, response was: BackappResponse[time=2024-04-15T19:30:37.167862151, message=hardcoded-default-backapp-message, homeworkOwner=Dézsi Lajos, hostAddress=172.22.0.3, extraImageData=Cubix training]
frontend-1  | 2024-04-15T19:30:37.170Z  INFO 1 --- [nio-8080-exec-7] h.c.c.api.controller.FrontappController  : Response will be: FrontappResponse[msForReply=3, backappMessage=hardcoded-default-backapp-message, frontappHomeworkOwner=Dézsi Lajos, frontappHostAddress=172.22.0.2, backappHomeworkOwner=Dézsi Lajos, backappHostAddress=172.22.0.3, doExtraImageDataMatch=true]

